name: Deploy VuePress 2 to GitHub Pages

on:
  push:
    branches:
      - master  # 监听 master 分支的推送事件

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 安装最新版本的 Node.js
      - name: Setup Node.js (latest version)
        uses: actions/setup-node@v4
        with:
          node-version: 'node'  # 获取最新版本的 Node.js

      # 启用 Corepack 并安装最新版本的 Yarn
      - name: Setup Yarn with Corepack
        run: |
          corepack enable
          corepack prepare yarn --activate  # 安装并激活最新版本的 Yarn

      # 安装依赖并禁止修改 lockfile
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 构建 VuePress 项目
      - name: Build VuePress site
        run: yarn build

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: .vuepress/dist
