name: Deploy VuePress 2 to GitHub Pages

on:
    push:
      branches:
        - master  # 监听 master 分支
      paths:
        - '**'        # 监听所有文件的变动
        - '!images/**' # 排除 images 文件夹

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 安装最新版本的 Node.js
      - name: Setup Node.js (latest version)
        uses: actions/setup-node@v4
        with:
          node-version: '23.2.0'

      # 安装依赖并禁止修改 lockfile
      - name: Install dependencies
        run: |
            npm install

      # 构建 VuePress 项目
      - name: Build VuePress site
        run: npm run build

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: .vuepress/dist
